### ISSUE TITLE
Module 3 - Building and Deploying to Production lab task 4

### ISSUE THREAD

**Issue by Alaabahr** [Microsoft/PartsUnlimited#163]
In the Module 3 - Building and Deploying to Production lab task 4, you have to import the build definition but in the new UI I can't find the import button and when trying to import the file to the task group I'm getting the below error: "Import of task group failed with error TypeError: Unable to get property 'map' of undefined or null reference"

**Comment by eamonnk** [comment]
Hi Alaabahr, 

The UI has changed so that the Import build pipeline option is now only present after you create a new build pipeline. This is similar in functionality as when importing a release pipeline in the next task in the lab. We'll need to update the steps to reflect the changes but in the meantime if you create a new build pipeline, then just save that, you don't need to configure anything. Then under Pipelines > Builds  > + New,  there should be an option to import a pipeline. That should allow you to import and continue on, there have been some general UI changes, but you should be able to work through the steps as is , while we get them updated. Sure let us know if that works for you or if you still have problems with it.

Thanks,
Eamonn

**Comment by eamonnk** [comment]
Hi, 

The lab steps have been updated for this lab,  [CI and CD with Azure DevOps - Quickstart](http://microsoft.github.io/PartsUnlimited/pandp/200.1x-PandP-CICDQuickstartwithVSTS.html). They address the build import steps issue flagged here and are updated for the recent UI changes and there's also an update to the release pipeline definition file to address an issue that was present in it.

Thanks,
Eamonn
