### ISSUE TITLE
No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

### ISSUE THREAD

**Issue by sleepingAgain** [Microsoft/PartsUnlimited#18]
I followed the instructions and I got this error when running the app.
Stack Trace: 
[InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9920760
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

This is the project.json file

  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
    "EntityFramework.SqlServer": "7.0.0-beta4",
    "EntityFramework.Commands": "7.0.0-beta4",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Microsoft.Framework.OptionsModel": "1.0.0-beta4"
  },
  "commands": {
    "ef": "EntityFramework.Commands"
  },
  "frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
    }
  }
}

This is the output of dvnm list.
dnvm list
Active Version     Runtime Architecture
------ -------     ------- ------------
 1.0.0-beta5 clr     x64

*  1.0.0-beta5 clr     x86     default

 1.0.0-beta5 coreclr x64

 
0.0-beta5 coreclr x86

I don't have experience with .NET, and I want to run this app for experimentation purposes.

Thank you.

**Comment by EMaher** [comment]
You are seeing this error message because you have the beta5 clr installed, but the project is set to use the beta4 clr. See https://github.com/aspnet/Home/issues/650 if you want further details.  To get the project to work install the beta 4 version.  I believe the command is 'dnvm install 1.0.0-beta4'.  There are lots of great articles at http://docs.asp.net/en/latest/ for someone new to ASP.NET 5.

I've opened issue #22 to port the code in master to beta5 so people won't run into this issue on a regular basis.

Thanks,
Elizabeth
